# Generated by Django 3.2.4 on 2021-08-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Formal (Public Sector)', 'Formal (Public Sector)'), ('Informal (Public Sector)', 'Informal (Private Sector)')], max_length=30, null=True),
        ),
    ]
