# Generated by Django 3.2.4 on 2021-08-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_first_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('1', 'Formal (Public Sector)'), ('2', 'Informal (Private Sector)')], max_length=30, null=True),
        ),
    ]
