# Generated by Django 3.2.4 on 2021-08-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mda_type', models.CharField(blank=True, choices=[('1', 'Grace Hospital'), ('2', 'Gifted Hospice'), ('3', 'Tranquil Hospital')], max_length=30, null=True)),
                ('employment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
