# Generated by Django 3.2.4 on 2021-08-17 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='plan_type',
            field=models.CharField(choices=[('1', 'Formal (Public Sector)'), ('2', 'Informal (Private Sector)')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
