# Generated by Django 3.2.4 on 2021-08-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_first_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.lga')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.country')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Rather not say')], max_length=30, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'AB'), ('4', 'O')], max_length=30, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=50, null=True)),
                ('next_of_kin_phone_no', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_with_kin', models.CharField(blank=True, choices=[('1', 'Cousin'), ('2', 'Nephew'), ('3', 'other')], max_length=50, null=True)),
                ('choose_plan', models.CharField(blank=True, choices=[('1', 'Public Sector Plan'), ('2', 'Public Sector Plan')], max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, choices=[('1', 'University of Ibadan College of Medicine'), ('2', 'Obafemi Awolowo University'), ('3', 'Ahmadu Bello University Faculty of Medicine'), ('4', 'University of Lagos College of Medicine'), ('5', 'Lagos State University College of Medicine'), ('6', 'Nsukka Faculty of Medical Sciences'), ('7', 'University of Ilorin College of Health Sciences'), ('8', 'Delta State University'), ('9', ' Niger Delta University College of Health Sciences'), ('10', 'Imo State University Faculty of Medicine')], max_length=50, null=True)),
                ('genotype', models.CharField(blank=True, choices=[('1', 'AA'), ('2', 'AO'), ('3', 'BB'), ('4', 'BO'), ('5', 'AB'), ('6', 'OO')], max_length=30, null=True)),
                ('religion', models.CharField(blank=True, choices=[('1', 'Christian'), ('2', 'Muslim'), ('3', 'other')], max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('1', 'Single'), ('2', 'Married')], max_length=50, null=True)),
                ('no_of_dependants', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, null=True)),
                ('preferred_primary_hcp_lga', models.CharField(blank=True, choices=[('1', 'Ajeromi-Ifelodun'), ('2', 'Abuja Municipal Area Council\t'), ('3', 'Aguata'), ('4', 'Awgu')], max_length=50, null=True)),
                ('preferred_primary_hcp', models.CharField(blank=True, choices=[('1', 'Sancta Maria Specialist & Mat.'), ('2', 'Abia State University Teaching Hospital'), ('3', 'Federal Medical Centre, Umuahia'), ('4', 'Life Care Clinics Ltd')], max_length=50, null=True)),
                ('date_of_employment', models.DateTimeField()),
                ('spouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_dob', models.DateTimeField()),
                ('spouse_sex', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Rather not say')], max_length=50, null=True)),
                ('spouse_blood_group', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'AB'), ('4', 'O')], max_length=50, null=True)),
                ('spouse_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('child_name', models.CharField(blank=True, max_length=50, null=True)),
                ('child_dob', models.DateTimeField()),
                ('child_gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Rather not say')], max_length=50, null=True)),
                ('child_blood_group', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'AB'), ('4', 'O')], max_length=50, null=True)),
                ('child_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('principal_category', models.CharField(blank=True, choices=[('1', 'Cousin'), ('2', 'Nephew'), ('3', 'other')], max_length=50, null=True)),
                ('diabetes', models.CharField(blank=True, choices=[('1', 'type 1'), ('2', 'type 2'), ('3', 'Gestational')], max_length=50, null=True)),
                ('hypertension', models.CharField(blank=True, choices=[('1', 'Primary'), ('2', 'Secondary')], max_length=50, null=True)),
                ('sickle_cell', models.CharField(blank=True, choices=[('1', 'Sickle Cell Anemia (SS)'), ('2', 'Sickle Hemoglobin-C Disease (SC)'), ('3', 'Sickle Beta-Plus Thalassemia'), ('4', 'Sickle Beta-Zero Thalassemia')], max_length=50, null=True)),
                ('cancer', models.CharField(blank=True, choices=[('1', 'Carcinoma'), ('2', 'Sarcoma'), ('3', 'Leukemia'), ('4', 'Lymphoma')], max_length=50, null=True)),
                ('kidney_issue', models.CharField(blank=True, choices=[('1', 'Kidney Stones'), ('2', 'Chronic Kidney Disease'), ('3', 'Urinary tract infections'), ('4', 'Glomerulonephritis')], max_length=50, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.country')),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.lga')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.state')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.town')),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.state'),
        ),
    ]
