# Generated by Django 3.2.4 on 2021-08-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_auto_20210818_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='child_dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='spouse_dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
