# Generated by Django 3.2.4 on 2021-08-19 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
