# Generated by Django 3.2.4 on 2021-08-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_registration_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mda_name', models.CharField(blank=True, choices=[('1', 'Domain Hospital'), ('2', 'Western Hospice'), ('3', 'Daniel Hospital')], max_length=30, null=True)),
                ('employment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('nim', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
