# Generated by Django 3.2.4 on 2021-08-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_informal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
